[project]
name = "rym-to-spotify"
version = "0.1.0"
description = ""
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "beautifulsoup4>=4.13.3",
    "nodriver>=0.45.1",
    "spotipy>=2.25.1",
]
